/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:27cf95ff-033f-40c9-a289-dcee4f53ad82",
    "aws_cognito_region": "eu-central-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "bd43683d5e0545aa9ec7589a87d9419b",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
